### PR TITLE
ripgrep: new package at 11.0.1

### PR DESCRIPTION
**Pull request by naltun**

### CODE REVIEW

**Comment by naltun** [comment]
@dylanaraps @konimex don't actually merge this just yet (if you intend to). I need to check why 9582296 is not from me.

**Comment by naltun** [comment]
Fubar'd

Redo

**Comment by konimex** [comment]
Looking at the [patch e-mail](https://github.com/kisslinux/repo/commit/958229601e69fd1bc6b0d30c6bd84e21259b15ea.patch), it seems you didn't set your e-mail and name properly.

**Comment by naltun** [comment]
@konimex I think you are right. Please review #39.

**Pull request closed without merging**
