### PR TITLE
various packages: fix build with clang, part 2

### PR DESCRIPTION
**Pull request by konimex**
The busybox patch is needed for Clang, otherwise ash will segfault. (I think) it shouldn't affect GCC, since Dilyn included it in his kiss-repo fork.

As for OpenSSL, I'm not sure about using the `$CC` approach or detecting Clang instead, since OpenSSL has separated profiles for `x86_64-linux` and `x86_64-linux-clang`. However, based on my tests and doing diff between the two logs (`x86_64-linux` and `x86_64-linux-clang`, both using `CC=/usr/bin/cc` as I don't want ccache to interfere), I don't think there are meaningful differences. https://termbin.com/50wm

### CODE REVIEW

**Comment by dylanaraps** [comment]
For busybox can we not just detect `clang` via `$CC --version` and then set `-DBB_GLOBAL_CONST=''"` in `CFLAGS`?

**Comment by dylanaraps** [comment]
One more query. What happens with openssl if `CC=clang`? The export line just sets `CC=cc` if empty, just wondering.

**Comment by konimex** [comment]
Unfortunately the CFLAGS you suggested don't work here, it still segfaults from my end.

As for OpenSSL, it just built without any complaints. With CC=clang and profile x86_64-linux.

**Comment by dylanaraps** [comment]
> As for OpenSSL, it just built without any complaints. With CC=clang and profile x86_64-linux.

So what's the point of defining `CC` if unset? What does it default to otherwise? Apologies
for the questions. Just trying to understand. 

> Unfortunately the CFLAGS you suggested don't work here, it still segfaults from my end.

Darn. I'm reluctant to apply the patch as it disables optimizations (The UB) when compiling
with GCC. We *could* conditionally apply it to clang if there's no other solution to the
problem.

**Comment by dylanaraps** [comment]
Pushed the patch but made it only apply when `$CC --version` reports `*clang*`. I wonder if upstream
are willing to fix this issue. I checked the git log and there are various clang/llvm fixes already.

**Pull request closed without merging**
