### PR TITLE
new package: python2

### PR DESCRIPTION
**Pull request by shizonic**

### CODE REVIEW

**Comment by konimex** [comment]
Please put it in `public/` instead of the main `extra/` tree.

**Comment by shizonic** [comment]
Done

**Comment by dylanaraps** [comment]
Why do we need this? I'd rather not have Python 2 at all.

**Comment by shizonic** [comment]
Yeah same here, but I guess there are gonna be some pkgs which depend on it. Your decision if you merge it.

**Comment by dylanaraps** [comment]
We should wait until then (Leave this PR open) and if possible try to avoid the dependency when it arises.

**Comment by shizonic** [comment]
Okay. Agreed.

**Comment by dylanaraps** [comment]
Needed for `nodejs`. :+1:

**Pull request merged**
