### PR TITLE
musl: add innetgr stub

### PR DESCRIPTION
**Pull request by dilyn-corner**
`polkit` has a set of patches used by [Solus](https://dev.getsol.us/T4824) that enable the use of an alternative backend besides javascript. What this enables is the ability for KISS-kde to drop `mozjs` entirely in favor of a far simpler keyfile, speeding everything up (and we no longer have to build an entire javascript engine for user permission policies!) and making KISS-kde far easier to maintain. Unfortunately, the creator of the patches that enable this was presumptuous about whether users would be on `glibc`. A [patch](https://www.openwall.com/lists/musl/2012/05/16/2) was made to solve an analogous problem that `polkit` upstream solved, eight years ago. With this patch applied, `innetgr` merely returns null and `polkit` builds just fine with the Solus patches! Of course, this renders netgroups useless, but KISS-kde users are presumably uninterested in this 'feature'. Looking through the mailing list, it's unclear to me why this patch was never upstreamed. Until it is, I would love for this small stub to be added to `repo/core/musl` so that I don't have to carry along a copy of `musl` in KISS-kde (very selfish, I know). 

I'll probably tap Rich Felker in a couple of days to ask about this patch and why it wasn't merged, so you are more than welcome to hold off on this until then.

### CODE REVIEW

**Comment by dylanaraps** [comment]
Not sure if you've seen these:

- https://gitlab.freedesktop.org/polkit/polkit/-/issues/14
- https://gitlab.freedesktop.org/polkit/polkit/-/merge_requests/10

**Comment by dilyn-corner** [comment]
Oh, I wasn't super clear; innetgr is added in the Solid patches; we're already making use of the Alpine patch you linked to. Ideally I'd like to rewrite the Solus patches (from what I know of C they aren't... Good), and until then getting them working as-is is the most important. 

That last link you posted I had *not* seen, however, and looks promising. I'll see if I can work with it!

**Comment by dylanaraps** [comment]
I'm reluctant to push stubs or larger extensions to the libc (such as libexecinfo, libuargp/argp-standalone, fts, obstack, ...). For example, libexecinfo being installed breaks builds for some packages (#213, https://github.com/kisslinux/repo/commit/390d2f070fbda51f55b300bb328bf551a370ed7d, not sure about exact depth of issue). Specifically with innetgr,  I don't know how many packages conditionally make use this function. With the stub available the "true" code paths will be hit and I'm unsure if any issues will arise... 

I'm sure this can be fixed in polkit itself (or the innetgr stub merged upstream).

**Comment by jedahan** [comment]
note that i use fwupd, which requires polkit (though there is a patch to remove it). I'd be happy to test with stubs to see if it works still.

**Comment by dylanaraps** [comment]
Any news?

**Pull request closed without merging**
