### PR TITLE
Update version of zlib

### PR DESCRIPTION
**Pull request by max12mx13**
This is blocking install, 1.2.11 is not up anymore

### CODE REVIEW

**Comment by aabacchus** [comment]
#383 #386

**Comment by max12mx13** [comment]
Sorry, my fault for not checking, thanks for the help!
Just out of interest, what has happened to this repo?

**Comment by aabacchus** [comment]
Dylan's gone on a hiatus from public development of KISS, probably for his mental health. The [unofficial] community is still going strong though.

**Comment by max12mx13** [comment]
Oh, that's unfortunate, do you think I should leave this pr here for when he comes back or close it.

**Comment by aabacchus** [comment]
That's up to you - but if you leave it here, you'll need to also update the checksums:
```
kiss c zlib
```

**Pull request closed without merging**
