### PR TITLE
[WIP] ffmpeg: new package at 4.1.4

### PR DESCRIPTION
**Pull request by konimex**
In `ffmpeg`, many dependencies will be required *if* we enable all {en,de}coders. These are the [options](https://termbin.com/tyl4).

Before we go on ahead building all its dependencies, what external libraries should we enable *by default*?

Arch enables [these](https://gist.github.com/konimex/5cb254c52e21e02e35617b1cedebe865), Void enables [these](https://gist.github.com/konimex/7702b137049b10748015df0eeccef50a), and last but not least, [Alpine](https://gist.github.com/konimex/b5abf009e2769e175eb103c9afd6b7fd).

### CODE REVIEW

**Comment by dylanaraps** [comment]
LGTM so far :+1: 

Options we should enable (incomplete list, will look into the others):

```
    --enable-libass \
    --enable-libfreetype \
    --enable-fontconfig \
    --enable-gpl \
    --enable-libvpx \
    --enable-libx264 \
    --enable-libx265 \
```

**Comment by protonesso** [comment]
@dylanaraps you can pass `--enable-gpl --enable-version3`

**Comment by dylanaraps** [comment]
We could enable everything and let `ffmpeg` figure it out (this also means commenting out whatever we deem as optional in the `depends` file).

**Comment by konimex** [comment]
Enabling all options will just make it fail for every dependencies not met.

At the very least, we can see Gentoo's [ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/media-video/ffmpeg/ffmpeg-4.1.1.ebuild) and see what we really need for the time being.

**Comment by dylanaraps** [comment]
LGTM :+1:

**Comment by konimex** [comment]
I've rebased my branch to `master` and moved current packages to `testing`, and I'm considering to merge this PR as is and open a new issue/project (if exists) to track our progress.

**Pull request merged**
