### PR TITLE
gcc: -static no longer overrides -pie

### PR DESCRIPTION
**Pull request by ioraff**
-static, by default, means static non-pie, regardless of whether -pie is specified or enabled by default.
-pie -static, for example, is now equivalent to -static-pie.
opening this PR as a handful of packages are using e.g. LDFLAGS="$LDFLAGS -static"

### CODE REVIEW

**Comment by dylanaraps** [comment]
Are we sure that this isn't fixed upstream?

- https://gcc.gnu.org/viewcvs/gcc?view=revision&revision=252351
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81498
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81523

**Comment by ioraff** [comment]
I thought the same, but something like
`
#include <stdio.h>

int main() {
        printf("%p\n", printf);
        return 0;
}
`
does not behave as expected.

for me, compiling with
- `gcc` prints random addresses.
- `gcc -static` prints the same address.
- `gcc -static-pie` prints random addresses

`gcc -static` after the patch prints random addresses.

**Comment by dylanaraps** [comment]
What about `-static -pie`?

**Comment by ioraff** [comment]
I don't know. I imagine it will print the same address, as -pie and -fPIE are supposed to be implicitly enabled.
I'd rather not recompile gcc to find out.

**Comment by dylanaraps** [comment]
It seems to work fine here?

```sh
-> gcc -o hello hello.c
-> ./hello
0x7f09e0190370
-> ./hello
0x7f6054679370

-> gcc -o hello hello.c -static
-> ./hello
0x4015d0
-> ./hello
0x4015d0

-> gcc -o hello hello.c -static-pie
-> ./hello
0x7f046b986810
-> ./hello
0x7fde52b8e810

-> gcc -o hello hello.c -static -pie
-> ./hello
0x4015d0
-> ./hello
0x4015d0
```

**Comment by ioraff** [comment]
> ```shell
> -> gcc -o hello hello.c -static
> -> ./hello
> 0x4015d0
> -> ./hello
> 0x4015d0
>
> -> gcc -o hello hello.c -static -pie
> -> ./hello
> 0x4015d0
> -> ./hello
> 0x4015d0
> ```

`-static` and `-static -pie` are printing the same thing, so the address is not randomized.

After the patch, I get this.
```shell
~ $ gcc -static test.c
~ $ ./a.out
0x7f2d395dd740
~ $ ./a.out
0x7f3200db5740
```

**Comment by dylanaraps** [comment]
Gotcha. Lets make the change. :+1:

**Comment by dylanaraps** [comment]
Merged here: https://github.com/kisslinux/repo/commit/96ad6fbe89791b0e0dd830b335ac3be2ac9851b0

Thanks! I also bumped the version so we can get the ball rolling.

**Comment by dylanaraps** [comment]
Interesting change post patch.

```sh
# With patch.
-> ldd /usr/bin/busybox
        ldd (0x7fef21f7e000)

# Without patch.
-> ldd /usr/bin/busybox
ldd: /usr/bin/busybox: Not a valid dynamic program
```

Any insights as to why this changed, if this is OK (still static(?)), etc? Will do my own research in the meantime.

**Pull request closed without merging**
